// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpsG_pUyH9MJ7-yWhc0BxpPr30cGGZxw',
    appId: '1:797102638375:web:d564c64c88634ab98b5502',
    messagingSenderId: '797102638375',
    projectId: 'babyshophub-87894',
    authDomain: 'babyshophub-87894.firebaseapp.com',
    databaseURL: 'https://babyshophub-87894-default-rtdb.firebaseio.com',
    storageBucket: 'babyshophub-87894.firebasestorage.app',
    measurementId: 'G-XPRK2CRQ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH4z1_sjEk11ZIcsD0PaxjBZ99DT2enGU',
    appId: '1:797102638375:android:570a2ceb5f67c9218b5502',
    messagingSenderId: '797102638375',
    projectId: 'babyshophub-87894',
    databaseURL: 'https://babyshophub-87894-default-rtdb.firebaseio.com',
    storageBucket: 'babyshophub-87894.firebasestorage.app',
  );
}
